function problemInfo = Problem_formulation(state, params, aoInfo)
%PROBLEM_FORMULATION 联合优化问题当前快照与约束检查

    spacingMatrix = diff(state.X, 1, 1);
    transmitPower = real(trace(state.W * state.W'));

    constraints = struct();
    constraints.userSet = struct( ...
        'subsetOfC', all(ismember(state.S, state.candidatePool)), ...
        'fixedCardinality', numel(state.S) == params.KServ, ...
        'satisfied', all(ismember(state.S, state.candidatePool)) && numel(state.S) == params.KServ);
    constraints.spacing = struct( ...
        'minSpacing', min(spacingMatrix(:)), ...
        'requiredSpacing', params.deltaMin, ...
        'satisfied', all(spacingMatrix(:) >= params.deltaMin - 1e-12));
    constraints.positionFeasibleSet = struct( ...
        'withinBounds', all(state.X(:) >= -1e-12) && all(state.X(:) <= params.Dy + 1e-12), ...
        'sorted', all(spacingMatrix(:) >= -1e-12), ...
        'satisfied', all(state.X(:) >= -1e-12) && all(state.X(:) <= params.Dy + 1e-12) && all(spacingMatrix(:) >= params.deltaMin - 1e-12));
    constraints.orientation = struct( ...
        'thetaSatisfied', all(state.theta(:) >= pi / 2 - 1e-12) && all(state.theta(:) <= pi + 1e-12), ...
        'phiSatisfied', all(state.phi(:) > -pi - 1e-12) && all(state.phi(:) <= pi + 1e-12), ...
        'satisfied', all(state.theta(:) >= pi / 2 - 1e-12) && all(state.theta(:) <= pi + 1e-12) && ...
            all(state.phi(:) > -pi - 1e-12) && all(state.phi(:) <= pi + 1e-12));
    constraints.power = struct('transmitPower', transmitPower, 'Pmax', params.Pmax, 'satisfied', transmitPower <= params.Pmax + 1e-12);
    constraints.allSatisfied = constraints.userSet.satisfied && constraints.spacing.satisfied && ...
        constraints.positionFeasibleSet.satisfied && constraints.orientation.satisfied && constraints.power.satisfied;

    problemInfo = struct();
    problemInfo.objective = state.sumRate;
    problemInfo.variables = struct('S', state.S, 'X', state.X, 'W', state.W, 'theta', state.theta, 'phi', state.phi, ...
        'candidatePool', state.candidatePool, 'iteration', state.iteration);
    problemInfo.constraints = constraints;
    problemInfo.ao = aoInfo;
    problemInfo.description = 'Problem (11) with AO order W -> (theta,phi) -> X -> S.';
end
